# Generated by Django 6.0.2 on 2026-02-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('normalized_url', models.URLField(blank=True)),
                ('mode', models.CharField(choices=[('PASSIVE', 'Passive'), ('AUTHORIZED', 'Authorized')], default='PASSIVE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('dependency_file_name', models.CharField(blank=True, max_length=255)),
                ('dependency_file_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
            ],
        ),
        migrations.CreateModel(
            name='CVEItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32)),
                ('cvss', models.CharField(blank=True, max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('fixed_in', models.CharField(blank=True, max_length=64)),
                ('references', models.JSONField(blank=True, default=list)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scans.component')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cves', to='scans.scan')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='scans.scan'),
        ),
    ]
